@echo off
echo Starting English Learning Assistant...
echo Setting API key...
set ENGLISH_LEARNING_ZHIPU_API_KEY=17e5feb32ed94b66823c9f9e0f188752.XOQDn1kygRTltwfD

echo API Key set to: %ENGLISH_LEARNING_ZHIPU_API_KEY:~0,8%...

echo Activating virtual environment and starting Streamlit...
cd /d "D:\GitHub\English-girl-learning"
"D:\GitHub\English-girl-learning\english-learning-env\Scripts\python.exe" -m streamlit run streamlit_app.py --server.port 8501

pause